name: hf-inference

services:
  api:
    image: haywoodsloan/hf-inference
    build:
      dockerfile: Dockerfile
    environment:
      - MODEL_NAME=haywoodsloan/ai-image-detector-dev-deploy
      - TASK_TYPE=image-classification
    ports:
      - 8000:80